### ISSUE TITLE
Add a Changelog from the Beginning of the Project

### ISSUE THREAD

**Issue by dalliard** [nextsport/nextsport#31]
For Reference [here](http://keepachangelog.com/en/0.3.0/) is explained why a Changelog is still good to provide. I will use the [GitHub Changelog API](https://github.com/levithomason/github-changelog-api) provided by @levithomason (which is a wrapper around the [GitHub Changelog Generator](https://github.com/skywinder/github-changelog-generator)) for easy CHANGELOG.md generation.

**Comment by levithomason** [comment]
Cool, LMK if you have any issues.  If this tool turns out to be used by people it would be nice to improve it along the way.
